# Config for triagebot

# Use labels that begin with `size-` to triage issues (eg: `size-s`, `size-m`)
# Set to `false` to disable
size: true

# List of users or teams to @mention to help triage
# Set to 'false' to disable
mention:
  - eyesonthefries
